prefixes = {
  b"-AZ2060-"         : "Azureus 2.0.6.0",
  b"-AZ3034-"         : "Azureus 3.0.3.4",
  b"-BOWA0"           : "BitBuddy",
  b"-BS582-"          : "BitSpirit 3.6.0.582",
  b"-BT0010-"         : "BitTorrent 1.0.x",
  b"-BT0090-"         : "BitTorrent 0.9.0+",
  b"-BT0150-"         : "BitTorrent 0.1.5.x",
  b"-CT1400-"         : "CTorrent 1.4.0",
  b"-DE13-----"       : "Deluge 1.3.x",
  b"-KT2210-"         : "KTorrent 2.2.1",
  b"-LT0350-"         : "libtorrent 0.35.x",
  b"-LT1000-"         : "libtorrent 1.0.x",
  b"-LT1130-"         : "libtorrent 1.1.3+",
  b"-LT1220-"         : "libtorrent 1.2.2+",
  b"-QT0000-"         : "Qt based client",
  b"-RT0000-"         : "Retriever",
  b"-S583-"           : "Shad0w's Experimental Client",
  b"-SB18--"          : "Swiftbit",
  b"-SN293-"          : "ShareNet",
  b"-SS194-"          : "SwarmScope",
  b"-SZB22-"          : "SurfNet",
  b"-T03B0-"          : "BitTornado 0.3.x",
  b"-T0130-"          : "BitTornado 0.13.x",
  b"-T0300-"          : "BitTornado 0.3.0.x",
  b"-TR2840-"         : "Transmission 2.84+",
  b"-TR2930-"         : "Transmission 2.93+",
  b"-UT3410-"         : "uTorrent 3.4.1",
  b"-UT430-"          : "uTorrent 4.3.0+",
  b"-UT443-"          : "uTorrent 4.4.3+",
  b"-UT450-"          : "uTorrent 4.5.0+",
  b"-UT3300-"         : "uTorrent 3.3.0",
  b"-UT3411-"         : "uTorrent 3.4.1+",
  b"-UT3420-"         : "uTorrent 3.4.2+",
  b"-UT350-"          : "uTorrent 3.5.0+",
  b"-UT360-"          : "uTorrent 3.6.0+",
  b"-UT370-"          : "uTorrent 3.7.0+",
  b"-UT380-"          : "uTorrent 3.8.0+",
  b"-XTS0-"           : "XanTorrent",
  b"-XX10-"           : "Xtorrent 1.x",
  b"-XX20-"           : "Xtorrent 2.x",
  b"-AZ"              : "Azureus",
  b"-BO"              : "BitBuddy",
  b"-BS"              : "BitSpirit",
  b"-BT"              : "BitTorrent",
  b"-CT"              : "CTorrent",
  b"-DE"              : "Deluge",
  b"-KT"              : "KTorrent",
  b"-LT"              : "libtorrent",
  b"-QT"              : "Qt based client",
  b"-RT"              : "Retriever",
  b"-S"               : "Shad0w's Experimental Client",
  b"-SB"              : "Swiftbit",
  b"-SN"              : "ShareNet",
  b"-SS"              : "SwarmScope",
  b"-SZB"             : "SurfNet",
  b"-TR"              : "Transmission",
  b"-T"               : "BitTornado",
  b"-UT"              : "uTorrent",
  b"-XT"              : "XanTorrent",
  b"-XX"              : "Xtorrent",
  b"A"                : "ABC",
  b"O"                : "Osprey Permaseed",
  b"Q"                : "BTQueue",
  b"R"                : "Tribler (versions < 6.1.0)",
  b"S"                : "Shadow's Experimental Client",
  b"SD"               : "Shadow's Experimental Client",
  b"SD-"              : "Shadow's Experimental Client",
  b"T"                : "BitTornado",
  b"U"                : "UPnP NAT Bit Torrent"
}

def peer_id_to_human_peer_id(peer_id):
  for prefix in prefixes:
    if peer_id.startswith(prefix):
      return prefixes[prefix]
  return None
